### ISSUE TITLE
how fix it

### ISSUE THREAD

**Issue by Mrcoinzer** [Optiminer/OptiminerZero#1]
not enough device memory available

**Comment by Optiminer** [comment]
Get a card with more memory. Your GPU must have at least 8GB or RAM.

**Comment by Mrcoinzer** [comment]
I have Ram 16G and gpu 4GB

**Comment by Optiminer** [comment]
Having 16G ram on the mainboard does not help at all. You need 8GB on the GPU with the current version of Optiminer/Zero.

**Comment by Mrcoinzer** [comment]
Thank you
