### ISSUE TITLE
Waiting for work from pool

### ISSUE THREAD

**Issue by backendmaster** [Optiminer/OptiminerZero#12]
Hello, this is same for 1.2 and sometimes for 2.0 
It says something like waiting for work from pool and stays that way.
It happens when software happen to miss the authenticate in the pool and is marked as "unauthorized".

What happens is that for the pool this is not valid client, and for the worker - there is not job from the pool and he waits...
Can you do it when it waits for 30 sec to restart the process? It is obvious new work is not going to arrive.

**Comment by Optiminer** [comment]
Please provide a log. Does this happen with all pools or just some? I wonder if this is a protocol error of the server or of the miner.

The miner already reconnects when it does not get any new message from the server for 5 minutes. I think in the stratum protocol there is no specific time interval in which the server is supposed to send new work. Therefore, the 5 minutes is relatively conservative.

**Comment by Optiminer** [comment]
Please follow up on https://github.com/Optiminer/OptiminerEquihash/issues/24
