### ISSUE TITLE
Optiminer miner not working on windows 7 64 bit

### ISSUE THREAD

**Issue by tnttct** [Optiminer/OptiminerZero#16]
I am trying to run optiminer on my HD 6990 card but when I start it say set gpu force 64bit to 1. I even did that but no success again same message please help

**Comment by Optiminer** [comment]
Follow the instructions on
https://github.com/Optiminer/OptiminerZero/blob/master/reportbug.md

**Comment by tnttct** [comment]
i have roboot my systems many times it happens always
i am using windows 7 ultimate service pack 1 with all updates
miner version is Optiminer/Zero 1.1.0 (C) Optiminer 2017
current driver version is 13.350.1005.0 but i have tried 15.x but the same error messsage appears with both.
my gpu is Hd 6990 4GB dual GPU.
[2018-01-02 21:30:11.986] [info] Optimi
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: AMD
  Device Name: Cayman
  Driver Version: 1411.4 (VM)
  Address bits: 32
  Available memory: 2147483648
  Has device specific faster kernel: No
Platform (-c) 0, Device (-d) 1:
  Platform Vendor: AMD
  Device Name: Cayman
  Driver Version: 1411.4 (VM)
  Address bits: 32
  Available memory: 2147483648
  Has device specific faster kernel: No
i have tried many options but always  gives same message this is the log
[2018-01-02 21:13:31.011] [info] Optiminer/Zero 1.1.0 (C) Optiminer 2017
[2018-01-02 21:13:31.026] [info] Connecting to zero.suprnova.cc:6568.
[2018-01-02 21:13:31.448] [error] Found device with 32-bit addressing. You need to set the environment variable 'GPU_FORCE_64BIT_PTR=1'!

**Comment by Optiminer** [comment]
You *cannot* mine Zero with these cards. They only have 2GB of memory. Try mining MNX or Zcash using
https://github.com/Optiminer/OptiminerEquihash
