### ISSUE TITLE
zero.suprnova.cc pool rejects user

### ISSUE THREAD

**Issue by pcollinsca47** [Optiminer/OptiminerZero#4]
When I modify mine.sh to my own suprnova user info on a 8G r9 390, submitted shares are rejected as from an unauthorized user. I tried several new and old  suprnova workers. This is on Linux 14.04 (Ethos) with their fglrx driver. (Unlikely a driver issue, but if you need it let me know how to get the driver version and I'll add it.)

My shell script:
# suprnova.cc
POOL=zero.suprnova.cc:6568
USER=smallpotatoes.zcoin
PASSWORD=x
./optiminer-zero -l mymine.log -d 0 -s $POOL -u $USER -p $PASSWORD

Error Message from pool:
2017-05-05 16:08:57.469] [info] [GPU0]  5.8 I/s 9.2 S/s (5s)
[2017-05-05 16:08:57.645] [warning] [GPU0] Share submission failed: unauthorized worker! (0 / 1)

Device info:
[2017-05-05 15:58:19.876] [info] Optiminer/Zero 1.0.0 (C) Optiminer 2017
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: AMD
  Device Name: Hawaii
  Driver Version: 1800.11 (VM)
  Address bits: 64
  Available memory: 8535408640
  GCN Support: Gen 2
  Has device specific faster kernel: No

[mymine.txt](https://github.com/Optiminer/OptiminerZero/files/980325/mymine.txt)

**Comment by Optiminer** [comment]
Double-check that smallpotatoes.zcoin is really the correct user and worker name. Did you really name the worker zcoin?

**Comment by pcollinsca47** [comment]
Yep I really named it zcoin. (Took me a bit to realize zcoin != zerocoin in the real world so the worker name is "ironic"). I also tried other workers I had such as smallpotatoes.opt188,

Here is a screen capture of my worker info:

<img width="776" alt="screen shot 2017-05-05 at 5 07 35 pm" src="https://cloud.githubusercontent.com/assets/7938058/25768230/db0b821c-31b5-11e7-8024-1c6c464e280e.png">


Of course I've looked at names and spelling so long I may be blind to a simple typo, apologies if that is the case. I've also sent this issue to suprnova.cc in case it's on their end.

**Comment by pcollinsca47** [comment]
Also tested mining zcash to smallpotates.zcoin worker name via optiminer-zcash and suprnova accepts shares for this ok. So suprnova.cc recognizes the work when I'm mining zcash.

used:
./optiminer-zcash -l suprnova-log.txt -s zec-us.suprnova.cc:2142  -u smallpotatoes.zcoin --password x

test log:
[suprnova-log.txt](https://github.com/Optiminer/OptiminerZero/files/980580/suprnova-log.txt)

**Comment by Optiminer** [comment]
That's very strange. Can you try the same command line for optiminer-zero (just with the different server/port). I get the same error if I specify an inexistent user. I even just tried changing
USER⁼smallpotatoes.zcoin
in mine.sh and it works fine!

**Comment by pcollinsca47** [comment]
Sure I'll do that in a few hours when i return home. 

--pc
pcollins@houstone.com

**Comment by Optiminer** [comment]
Closing as of no updates.
