### ISSUE TITLE
mining issue

### ISSUE THREAD

**Issue by p34567** [Optiminer/OptiminerZero#7]
Hello,

I have issue when setting miner to mine solo.

This is what I receive in optiminer window:

[info] Connecting to 127.0.0.1:23800.
[warning] Failed to parse server message. Closing connection.
[error] IO/Error communicating to 127.0.0.1

Node works fine, it connects to network.  Miner mines correctly with pool.

**Comment by Optiminer** [comment]
The miner only supports the stratum protocol. To solo-mine, you'd need a stratum proxy for Zero (afaik there is none) or setup your own pool.
